version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
      - echo Getting current active backend...
      - ACTIVE_BACKEND=$(aws ssm get-parameter --name "/blue-green-app/active-backend" --query "Parameter.Value" --output text)
      - echo Current active backend is $ACTIVE_BACKEND
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI:latest
      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Determining target environment for deployment...
      - |
        if [ "$ACTIVE_BACKEND" = "blue" ]; then
          TARGET_BACKEND="green"
          TARGET_SERVICE="blue-green-app-backend-green"
        else
          TARGET_BACKEND="blue"
          TARGET_SERVICE="blue-green-app-backend-blue"
        fi
      - echo Deploying to $TARGET_BACKEND environment
      - echo Updating ECS service $TARGET_SERVICE...
      - |
        aws ecs update-service \
          --cluster blue-green-app-backend-cluster \
          --service $TARGET_SERVICE \
          --desired-count 1 \
          --force-new-deployment
      - echo Waiting for service to become stable...
      - |
        aws ecs wait services-stable \
          --cluster blue-green-app-backend-cluster \
          --services $TARGET_SERVICE
      - echo Switching traffic to $TARGET_BACKEND...
      - |
        aws ssm put-parameter \
          --name "/blue-green-app/active-backend" \
          --value $TARGET_BACKEND \
          --overwrite
      - echo Scaling down old environment...
      - |
        if [ "$TARGET_BACKEND" = "green" ]; then
          OLD_SERVICE="blue-green-app-backend-blue"
        else
          OLD_SERVICE="blue-green-app-backend-green"
        fi
      - |
        aws ecs update-service \
          --cluster blue-green-app-backend-cluster \
          --service $OLD_SERVICE \
          --desired-count 0
      - echo Blue-Green deployment completed successfully!

artifacts:
  files:
    - '**/*'